spring:
  ####### Redis Config 注意！！！springboot3的redis前缀是spring.data.redis!!springboot2.x的redis配置是spring.redis 别踩坑！！#######
  cache:
    type: redis  # 指定缓存使用 Redis
  redis:
    lettuce:
      pool:
        # 连接池最大连接数(使用负值表示没有限制) 默认为8
        max-active: 8
        # 连接池中的最大空闲连接 默认为8
        max-idle: 8
        # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1
        max-wait: -1
        # 连接池中的最小空闲连接 默认为 0
        min-idle: 0
    sentinel:
      # 主节点的别名
      master: ${KITCHEN_REDIS_MASTER:mymaster}
      # sentinel服务的ip和端口
      nodes: ${KITCHEN_REDIS_NODES:127.0.0.1:16379,127.0.0.1:26379,127.0.0.1:36379} # 这里是sentinel实例
    password: ${KITCHEN_REDIS_PASSWORD:redis} # 如果有
    database: ${KITCHEN_REDIS_DATABASE:2}  # 数据库索引