# Server settings
server:
  tomcat:
    basedir: /var/tmp/kitchen/kitchen-web

# logging settings
logging:
  config: classpath:logback-spring.xml
  file:
    path: /var/tmp/kitchen/kitchen-web
####################################自定义配置##########################################
app:
  # 启用后，项目在启动时会打印数据库（Mysql和Redis）链接信息（包含密码）
  # 代码请参考
  enabledPrintConfig: ${KITCHEN_APP_ENABLE_PRINT_CONFIG:true}
####################################自定义配置##########################################
#管理员账号配置
admin:
  id: 10